### ISSUE TITLE
Sharehouse.app

### ISSUE THREAD

**Issue by jordiup** [RedBlood639/mailinbox#1]
Hi @RedBlood639, this is Jordi, from Sharehouse. 

I couldn't find your contact details but if you would like to circumvent the 10% Upwork fee I'm more than happy to continue. 

Next steps will be:
- Book in a time to catch up (early next week, 9am Helsinki == 4pm Sydney)
- I will walk you through the repository, our onboarding procedure and provide you with a README or other guidance

Here are some rendered UIs of what we're looking for :) 

https://www.figma.com/file/7aypbaLt0O4qHjutYcgcdC/Sharehouse-Messaging-Scope?node-id=0%3A1

Please shoot me an email here: jordi@sharehouse.app

**Comment by RedBlood639** [comment]
Hello @jordiup, How are you ?
Thank you for your message, and I am sorry late.
I just sent message via your email.
Please check and let me know.
Thank yu

**Comment by RedBlood639** [comment]
Solved this problem.
